---

- src: https://github.com/nemesisdesign/Stouts.postfix
  version: origin/develop
  name: Stouts.postfix

- src: https://github.com/highway7/ansible-ow-influxdb
  version: master
  name: ow-influxdb
